"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['bin/pct.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
            "includes":['scipy','numpy']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
      packages=['corpustools', 
                'corpustools.acousticsim',
                'corpustools.corpus',
                'corpustools.freqalt',
                'corpustools.funcload',
                'corpustools.prod',
                'corpustools.gui',
                'corpustools.symbolsim'],
    setup_requires=['py2app'],
)
